### ISSUE TITLE
some trouble existed in 'JP_3d_l_asp.m'

### ISSUE THREAD

**Issue by yayadian2012** [ydluo/qdyn#19]
Dear QDYN developers,

I found another issue during calculations. For the example 'JP_3d_l_asp.m', 'ox1' is empty for serial code and parallel code. 

Looking forward for your reply. Thank you very much!

**Comment by yayadian2012** [comment]
I use the newest version.

**Comment by martijnende** [comment]
Not yet, see #18

**Comment by yayadian2012** [comment]
ok, I know. Thank you!

**Comment by martijnende** [comment]
Since the opening of this issue, numerous changes have been made. The ox output has been revised and will soon be merged with the `master` branch (see #43), and the parallel execution needs to be tested and re-designed. It is unlikely that `JP_3d_I_asp.m` is still compatible with the latest code, so identifying this issue will not be possible anymore. I am therefore closing this issue, but if similar issues arise in the future a new ticket can be opened.
