### ISSUE TITLE
 Bad integer for item 8 in list input

### ISSUE THREAD

**Issue by kaiixing** [ydluo/qdyn#91]
#https://github.com/ydluo/qdyn/blob/e06edb1db4d402fbc4581e086a019d30e433cc56/src/qdyn.m#L521

The formatting parameters are inconsistent with the input parameters, cannot be run with MATLAB.

```
At line 46 of file input.f90 (unit = 15, file = 'qdyn000001.in')
    Mesh input complete
Fortran runtime error: Bad integer for item 8 in list input

Error termination. Backtrace:
#0  0x762c8ec23960 in ???
#1  0x762c8ec244d9 in ???
#2  0x762c8ec2510f in ???
#3  0x762c8ee6e5eb in ???
#4  0x762c8ee715aa in ???
#5  0x762c8ee722aa in ???
#6  0x63a23001aa05 in ???
#7  0x63a23001dd29 in ???
#8  0x63a22fff73ee in ???
#9  0x762c8e829d8f in __libc_start_call_main
	at ../sysdeps/nptl/libc_start_call_main.h:58
#10  0x762c8e829e3f in __libc_start_main_impl
	at ../csu/libc-start.c:392
#11  0x63a22fff7424 in ???
#12  0xffffffffffffffff in ???
```

**Comment by martijnende** [comment]
Already some time ago we've realised that the MATLAB wrapper is no longer up-to-date (#76), but since nobody in the team uses MATLAB, we decided to drop support entirely. This will be official in the upcoming version (3.0; #84), in which we remove all traces of MATLAB.

I recommend you use the Python wrapper instead, which has several documented examples and tutorials.

**Comment by kaiixing** [comment]
ok,I see.
